---
name: deploy to gh pages

on:
  workflow_call:
    inputs:
      runner:
        description: runner name
        type: string
        default: ubuntu-latest
        required: false
      environment:
        description: environment name
        type: string
        default: github-pages
        required: false
      path:
        description: path to be deployed
        type: string
        default: "."
        required: false

jobs:
  deploy:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # https://github.com/marketplace/actions/harden-runner
      - name: harden runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # https://github.com/marketplace/actions/configure-github-pages
      - name: setup pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      # https://github.com/marketplace/actions/upload-github-pages-artifact
      - name: upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: ${{ inputs.path }}

      # https://github.com/marketplace/actions/deploy-github-pages-site
      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
