---
name: megalinter

on:
  workflow_call:
    inputs:
      runner:
        description: runner name
        type: string
        default: ubuntu-latest
        required: false
      flavor:
        description: flavor
        type: string
        default: null
        required: false

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      # https://github.com/marketplace/actions/harden-runner
      - name: harden runner
        uses: step-security/harden-runner@v2.10.3
        with:
          egress-policy: audit

      # https://github.com/marketplace/actions/create-github-app-token
      - name: generate token
        id: generate-token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        with:
          app-id: ${{ secrets.github-app-id }}
          private-key: ${{ secrets.github-app-key }}

      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # TODO: setup megalinter for each flavor and run based on inputs.flavor
      # https://github.com/marketplace/actions/megalinter
      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/terraform@c217fe8f7bc9207062a084e989bd97efd56e7b9a # v8.0.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          # GITHUB_STATUS_REPORTER only works if VALIDATE_ALL_CODEBASE is false!
          GITHUB_STATUS_REPORTER: true
          REPORTERS_MARKDOWN_TYPE: simple
          SHOW_ELAPSED_TIME: false
          SHOW_SKIPPED_LINTERS: true
