---
name: renovate

on:
  workflow_dispatch:
    inputs:
      log-level:
        description: log-level
        type: string
        default: debug
        required: false
      dry-run:
        description: dry run
        type: string
        default: null
        required: false
  schedule:
    - cron: 0 */3 * * * # every 3 hours
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate-bot.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    uses: ./.github/workflows/run-renovate.yaml
    with:
      runner: ubuntu-latest
      configuration-file: .github/renovate-bot.json5
      dry-run: ${{ inputs.dry-run || 'null' }}
      log-level: ${{ inputs.log-level || 'debug' }}
    secrets:
      github-app-id: ${{ secrets.BOT_APP_ID }}
      github-app-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
